<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <Description>FFmpeg auto generated unsafe bindings for C#/.NET. A fork of Ruslan Balanukhin's FFmpeg.AutoGen which fixs the library call on android and more platforms.</Description>
    <GeneratePackageOnBuild Condition=" $(Configuration) == 'Release' ">true</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <NoWarn>108;169;618;1573;1591;1701;1702;1705;8981</NoWarn>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
	  <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

	<PropertyGroup>
		<!-- Build symbol package (.snupkg) to distribute the PDB containing Source Link -->
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<Authors>hexadecimal0x12e</Authors>
		<Company>nope</Company>
		<Copyright>Copyright © hexadecimal0x12e 2025 All rights reserved.</Copyright>
		<PackageProjectUrl>https://github.com/hexadecimal0x12e/FFmpeg.AutoGen_droidFix</PackageProjectUrl>
		<PackageId>FFmpeg_droidFix.AutoGen</PackageId>
	</PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="all" />
  </ItemGroup>
  
</Project>
