<Project Sdk="Microsoft.NET.Sdk">
	
  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0;net11.0</TargetFrameworks>
    <TargetFrameworks>$(TargetFrameworks);net10.0-ios;net11.0-ios</TargetFrameworks>
    <TargetFrameworks>$(TargetFrameworks);net10.0-maccatalyst;net11.0-maccatalyst</TargetFrameworks>
    <TargetFrameworks>$(TargetFrameworks);net10.0-android;net11.0-android</TargetFrameworks>
		<Description>FFmpeg auto generated unsafe bindings for C#/.NET. A fork of Ruslan Balanukhin's FFmpeg.AutoGen which fixs the library call on android and more platforms.</Description>
		<GeneratePackageOnBuild Condition=" $(Configuration) == 'Release' ">true</GeneratePackageOnBuild>
	</PropertyGroup>

	<PropertyGroup>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<NoWarn>108;169;618;1573;1591;1701;1702;1705;8981</NoWarn>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
		<WarningsAsErrors />
		<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
		<IsAotCompatible>true</IsAotCompatible>
	</PropertyGroup>

	<PropertyGroup>
		<!-- Build symbol package (.snupkg) to distribute the PDB containing Source Link -->
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<Authors>hexadecimal0x12e</Authors>
		<Company>nope</Company>
		<Copyright>Copyright © hexadecimal0x12e 2025 All rights reserved.</Copyright>
		<PackageProjectUrl>https://github.com/hexadecimal0x12e/FFmpeg.AutoGen_droidFix</PackageProjectUrl>
		<PackageId>FFmpeg_droidFix.AutoGen</PackageId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="all"   />
	</ItemGroup>

	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">
		<UseMaui>true</UseMaui>
	</PropertyGroup>
	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">
		<UseMaui>true</UseMaui>
	</PropertyGroup>
	<PropertyGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">
		<UseMaui>true</UseMaui>
	</PropertyGroup>

	<ItemGroup Condition="'$(UseMaui)' == 'true' ">
		<PackageReference Include="Microsoft.Maui.Controls" PrivateAssets="all"  />
	</ItemGroup>

</Project>